# Site settings
title:                  Joshua Soucie
description:            'Engineer, Hacker, Entrepreneur, Globetrotter'
url:                    'http://joshsoucie.com'
baseurl:                '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name:                 'Josh Soucie'
  email:                jlsoucie21@gmail.com
  twitter_username:     josh_soucie
  facebook_username:    joshsoucie
  github_username:      js-bone21
  linkedin_username:    joshuasoucie

defaults:
  -
    scope:
      path:              ''
      type:             'posts'
    values:
        layout:         'post'

# Build settings
destination:            _site
paginate:               10
permalink:              /:year/:title/
markdown:               kramdown
highlighter:            rouge

kramdown:
  # use Github Flavored Markdown
  input:                GFM
  # do not replace newlines by <br>s
  hard_wrap:            false

gems:                   ['jekyll-paginate']
exclude:                ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
